export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';

export const UPDATE_SHELF_REQUEST = 'UPDATE_SHELF_REQUEST';
export const UPDATE_SHELF_SUCCESS = 'UPDATE_SHELF_SUCCESS';
export const UPDATE_SHELF_FAIL = 'UPDATE_SHELF_FAIL';
